apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: staging
  labels:
    run: landing-page
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: landing-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      run: landing-page
  template:
    metadata:
      labels:
        run: landing-page
    spec:
      containers:
      - name: landing-page
        image: smufti21/staging-landing:latest
        ports:
          - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: landing-page-ingress
  namespace: staging
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: stlanding.sm21.xyz
    http:
      paths:
      #- path: /
      - backend:
          serviceName: landing-page
          servicePort: 80
